"use client"

import React, { useState, useEffect, useRef, Suspense } from "react"
import {
  Play,
  Square,
  Activity,
  CheckCircle2,
  AlertTriangle,
  Terminal,
  KanbanSquare,
  MessageSquare,
  Settings,
  Database,
  TrendingUp,
  Send,
  Cpu,
  Layers,
  DollarSign,
  XCircle,
  Plus,
  RefreshCw,
  Sliders,
  Eye,
  X,
  Check,
  Circle,
  ChevronDown,
  ChevronRight,
  Folder,
  FolderOpen,
  FolderTree,
  FileCode,
  Save,
  LayoutDashboard,
  History,
  ArrowRight
} from "lucide-react"

import { projectsData, ProjectConfig } from "@/lib/projects"
import { getProjectActivity } from "@/lib/projectActivity"

import { 
  Card, 
  CardHeader, 
  CardTitle, 
  CardDescription, 
  CardContent, 
  CardFooter 
} from "@/components/ui/card"

import { 
  Tabs, 
  TabsList, 
  TabsTrigger, 
  TabsContent 
} from "@/components/ui/tabs"

import { 
  Table, 
  TableBody, 
  TableCell, 
  TableHead, 
  TableHeader, 
  TableRow 
} from "@/components/ui/table"

import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import PageLayout from "@/components/PageLayout"

// Types
interface LogMessage {
  id: string
  timestamp: string
  level: "info" | "warning" | "error" | "success"
  source: string
  message: string
}

interface ChatMessage {
  id: string
  sender: "user" | "agent"
  agentName?: string
  avatar?: string
  message: string
  timestamp: string
  status?: "running" | "done" | "waiting"
}

interface KanbanTask {
  id: string
  title: string
  agent: string
  agentAvatar: string
  status: "backlog" | "progress" | "auditing" | "verification" | "done"
  priority: "low" | "medium" | "high" | "critical"
  progress: number
}

interface HitlTicket {
  id: string
  taskId: string
  title: string
  agent: string
  agentAvatar: string
  description: string
  status: "pending" | "approved" | "rejected"
  timestamp: string
}

interface FileNode {
  name: string
  path: string
  type: "file" | "folder"
  children?: FileNode[]
}

// Mock project file tree (workspace/ sandbox structure)
const workspaceFileTree: FileNode[] = [
  {
    name: "src", path: "src", type: "folder", children: [
      {
        name: "app", path: "src/app", type: "folder", children: [
          { name: "page.tsx", path: "src/app/page.tsx", type: "file" },
          { name: "layout.tsx", path: "src/app/layout.tsx", type: "file" },
        ]
      },
      {
        name: "components", path: "src/components", type: "folder", children: [
          { name: "Header.tsx", path: "src/components/Header.tsx", type: "file" },
          { name: "Sidebar.tsx", path: "src/components/Sidebar.tsx", type: "file" },
        ]
      },
      {
        name: "lib", path: "src/lib", type: "folder", children: [
          { name: "db.ts", path: "src/lib/db.ts", type: "file" },
          { name: "utils.ts", path: "src/lib/utils.ts", type: "file" },
        ]
      },
    ]
  },
  { name: "package.json", path: "package.json", type: "file" },
  { name: "README.md", path: "README.md", type: "file" },
]

// Mock initial file contents keyed by path
const initialFileContents: Record<string, string> = {
  "src/app/page.tsx": `export default function Page() {\n  return (\n    <main>\n      <h1>Welcome to the factory build</h1>\n    </main>\n  )\n}\n`,
  "src/app/layout.tsx": `export default function RootLayout({ children }: { children: React.ReactNode }) {\n  return (\n    <html lang="en">\n      <body>{children}</body>\n    </html>\n  )\n}\n`,
  "src/components/Header.tsx": `export default function Header() {\n  return <header className="border-b p-4">Factory Header</header>\n}\n`,
  "src/components/Sidebar.tsx": `export default function Sidebar() {\n  return <aside className="w-64 border-r">Sidebar</aside>\n}\n`,
  "src/lib/db.ts": `import { Pool } from "pg"\n\nexport const pool = new Pool({\n  connectionString: process.env.DATABASE_URL,\n})\n`,
  "src/lib/utils.ts": `export function cn(...classes: (string | undefined | false)[]) {\n  return classes.filter(Boolean).join(" ")\n}\n`,
  "package.json": `{\n  "name": "generated-app",\n  "version": "0.1.0",\n  "scripts": {\n    "dev": "next dev",\n    "build": "next build"\n  }\n}\n`,
  "README.md": `# Generated Application\n\nThis codebase was generated by the Dark Factory pipeline.\n`,
}

import { useRouter, useSearchParams } from "next/navigation"

function WorkspaceContent() {
  const router = useRouter()
  const searchParams = useSearchParams()
  const selectedProjectId = searchParams?.get("projectId") || "jsrm_erp"
  const currentProject = projectsData.find(p => p.id === selectedProjectId) || projectsData[0]
  const projectActivity = getProjectActivity(currentProject.id)

  // Active tab state — this is the project-wise dashboard, so it opens on the Overview tab
  const activeTab = searchParams?.get("tab") || "overview"
  const setActiveTab = (tab: string) => {
    const params = new URLSearchParams(searchParams?.toString() || "")
    params.set("tab", tab)
    router.push(`/workspace?${params.toString()}`)
  }

  // System stats state
  const [cpuUsage, setCpuUsage] = useState<number>(42)
  const [memoryUsage, setMemoryUsage] = useState<number>(68)
  const [activeAgentsCount, setActiveAgentsCount] = useState<number>(3)
  const [latency, setLatency] = useState<number>(124)
  const [totalCost, setTotalCost] = useState<number>(142.50)

  // HITL (Human-in-the-loop) Approval States
  const [hitlTickets, setHitlTickets] = useState<HitlTicket[]>([
    {
      id: "hitl-1",
      taskId: "t1",
      title: "Sync Staging Database Schema",
      agent: "Cattlesync Agent",
      agentAvatar: "🐮",
      description: "Automated schema diff matches target staging. Operator approval is required to apply the DDL migrations.",
      status: "pending",
      timestamp: "15:07:12"
    },
    {
      id: "hitl-2",
      taskId: "t3",
      title: "Deploy ERP core module API",
      agent: "ERP Deployer",
      agentAvatar: "🚀",
      description: "Automated test validation has passed. Production deployment authorization is requested for the ERP core module.",
      status: "pending",
      timestamp: "15:07:30"
    }
  ])

  // Kanban Tasks (5-phase SDLC matching)
  const [tasks, setTasks] = useState<KanbanTask[]>([
    {
      id: "t1",
      title: "Sync local database schema to staging server",
      agent: "Cattlesync Agent",
      agentAvatar: "🐮",
      status: "verification",
      priority: "high",
      progress: 90
    },
    {
      id: "t2",
      title: "Investigate Jest test runner memory leaks",
      agent: "QA Architect",
      agentAvatar: "🔍",
      status: "progress",
      priority: "medium",
      progress: 65
    },
    {
      id: "t3",
      title: "Deploy ERP Dashboard core module API",
      agent: "ERP Deployer",
      agentAvatar: "🚀",
      status: "auditing",
      priority: "critical",
      progress: 80
    },
    {
      id: "t4",
      title: "Refactor telemetry pipeline hooks",
      agent: "Telemetry Agent",
      agentAvatar: "📈",
      status: "progress",
      priority: "low",
      progress: 15
    },
    {
      id: "t5",
      title: "Configure security secrets rotating cron",
      agent: "SecOps Agent",
      agentAvatar: "🛡️",
      status: "backlog",
      priority: "high",
      progress: 0
    }
  ])

  // Logs state
  const [logs, setLogs] = useState<LogMessage[]>([
    { id: "l1", timestamp: "15:07:05", level: "info", source: "System", message: "Initialize Agentic Software Factory orchestrator..." },
    { id: "l2", timestamp: "15:07:06", level: "success", source: "DB", message: "Connected to PostgreSQL database instance." },
    { id: "l3", timestamp: "15:07:12", level: "info", source: "Cattlesync", message: "Cattlesync Agent triggered for schema migration task." },
    { id: "l4", timestamp: "15:07:15", level: "warning", source: "QA Architect", message: "Jest test suite reported 12% memory usage elevation." },
    { id: "l5", timestamp: "15:07:30", level: "info", source: "System", message: "HITL event created: ERP Deployer requires production deployment approval." },
  ])

  const [logFilter, setLogFilter] = useState<string>("all")

  // Chat state
  const [chatInput, setChatInput] = useState<string>("")
  const [chatMessages, setChatMessages] = useState<ChatMessage[]>([
    {
      id: "c1",
      sender: "agent",
      agentName: "Factory Lead",
      avatar: "⚙️",
      message: "Welcome operator! I'm Factory Lead. What modules or automated pipelines would you like to run today? You can monitor telemetry, view code tasks on the Kanban board, or check live logs.",
      timestamp: "15:07:10"
    }
  ])

  const [isTyping, setIsTyping] = useState<boolean>(false)

  // Factory Settings state
  const [companyName, setCompanyName] = useState<string>("JSRM Enterprises Ltd.")
  const [missionScope, setMissionScope] = useState<string>("Enterprise resource planning automation with a focus on supply chain transparency and autonomous fiscal reconciliation.")
  const [voiceTone, setVoiceTone] = useState<string>("Technical Professional (High Density)")
  const [strictnessLevel, setStrictnessLevel] = useState<number>(4)
  const [unitTestsEnforced, setUnitTestsEnforced] = useState<boolean>(true)
  const [docsGenerationEnforced, setDocsGenerationEnforced] = useState<boolean>(true)
  const [ddasEnabled, setDdasEnabled] = useState<boolean>(false)
  const [isSavingSettings, setIsSavingSettings] = useState<boolean>(false)

  // Pre-Flight Model-to-Role Mapping
  const [roleMappings, setRoleMappings] = useState({
    orchestrator: "anthropic/claude-3-5-sonnet",
    coder: "anthropic/claude-3-5-sonnet",
    auditor: "google/gemini-1.5-pro",
    deployer: "openai/gpt-4o-mini",
  })

  // Skills / MCP Tools
  const [mcpSkills, setMcpSkills] = useState([
    { id: "term", name: "terminal-executor", desc: "Execute safe CLI actions in sandbox environment", active: true },
    { id: "fs", name: "filesystem-manager", desc: "Write, edit, and read files in work directory", active: true },
    { id: "web", name: "web-searcher", desc: "Fetch up-to-date documentation and packages", active: true },
    { id: "git", name: "git-integrator", desc: "Perform commits, branch creation and merge staging", active: true },
    { id: "browser", name: "playwright-browser", desc: "Simulate Chrome page loads & DOM validations", active: false }
  ])

  // File Manager state
  const [expandedFolders, setExpandedFolders] = useState<Set<string>>(new Set(["src", "src/app"]))
  const [selectedFilePath, setSelectedFilePath] = useState<string>("src/app/page.tsx")
  const [fileContents, setFileContents] = useState<Record<string, string>>(initialFileContents)
  const [draftContent, setDraftContent] = useState<string>(initialFileContents["src/app/page.tsx"])
  const [fileSaveStatus, setFileSaveStatus] = useState<string | null>(null)

  const isFileDirty = draftContent !== (fileContents[selectedFilePath] ?? "")

  const handleToggleFolder = (path: string) => {
    setExpandedFolders(prev => {
      const next = new Set(prev)
      if (next.has(path)) {
        next.delete(path)
      } else {
        next.add(path)
      }
      return next
    })
  }

  const handleSelectFile = (path: string) => {
    if (path === selectedFilePath) return
    if (isFileDirty) {
      const confirmed = window.confirm(`Discard unsaved changes to ${selectedFilePath}?`)
      if (!confirmed) return
    }
    setSelectedFilePath(path)
    setDraftContent(fileContents[path] ?? "")
    setFileSaveStatus(null)
  }

  const handleSaveFile = () => {
    setFileContents(prev => ({ ...prev, [selectedFilePath]: draftContent }))

    const now = new Date()
    const timestamp = now.toTimeString().split(" ")[0]
    setLogs(prev => [
      ...prev,
      {
        id: Math.random().toString(),
        timestamp,
        level: "success",
        source: "Operator",
        message: `Manual edit saved: ${selectedFilePath}`
      }
    ])

    setFileSaveStatus("Saved")
    setTimeout(() => setFileSaveStatus(null), 2500)
  }

  const handleDiscardFileEdit = () => {
    setDraftContent(fileContents[selectedFilePath] ?? "")
    setFileSaveStatus(null)
  }

  useEffect(() => {
    const loadSettings = () => {
      const storedStrictness = localStorage.getItem("sdlc_strictness") || "4"
      setStrictnessLevel(Number(storedStrictness))
    }
    loadSettings()
    window.addEventListener("apex-settings-update", loadSettings)
    return () => {
      window.removeEventListener("apex-settings-update", loadSettings)
    }
  }, [])

  // Sync settings when project changes
  useEffect(() => {
    if (currentProject) {
      setCompanyName(currentProject.companyName)
      setMissionScope(currentProject.missionScope)
      
      // Update initial chat message based on the project's agent
      setChatMessages([
        {
          id: "c1",
          sender: "agent",
          agentName: currentProject.agentName,
          avatar: currentProject.agentIcon,
          message: `Welcome operator! I am the ${currentProject.agentName} (${currentProject.agentIcon}) dedicated to ${currentProject.name}. How can I assist you in this workspace today?`,
          timestamp: new Date().toTimeString().split(' ')[0]
        }
      ])
    }
  }, [selectedProjectId])

  // Auto-scroll for logs and chat
  const logsEndRef = useRef<HTMLDivElement>(null)
  const chatEndRef = useRef<HTMLDivElement>(null)

  useEffect(() => {
    if (activeTab === "logs") {
      logsEndRef.current?.scrollIntoView({ behavior: "smooth" })
    }
  }, [logs, activeTab])

  useEffect(() => {
    chatEndRef.current?.scrollIntoView({ behavior: "smooth" })
  }, [chatMessages])

  // Simulate Telemetry adjustments
  useEffect(() => {
    const interval = setInterval(() => {
      setCpuUsage(prev => {
        const delta = Math.floor(Math.random() * 9) - 4
        return Math.min(Math.max(prev + delta, 15), 95)
      })
      setMemoryUsage(prev => {
        const delta = Math.floor(Math.random() * 3) - 1
        return Math.min(Math.max(prev + delta, 50), 85)
      })
      setLatency(prev => {
        const delta = Math.floor(Math.random() * 15) - 7
        return Math.min(Math.max(prev + delta, 90), 220)
      })
    }, 3000)
    return () => clearInterval(interval)
  }, [])

  // Auto-generate some log entries occasionally
  useEffect(() => {
    const interval = setInterval(() => {
      const sources = ["System", "Cattlesync", "ERP Deployer", "SecOps Agent", "Telemetry Agent"]
      const source = sources[Math.floor(Math.random() * sources.length)]
      
      const infos = [
        "Analyzing project directory schema patterns.",
        "Resource utilization metrics flushed to telemetry storage.",
        "Checking health endpoints for deployment services.",
        "Scraping logs from local agent workers.",
        "Updating build status mapping details."
      ]
      
      const now = new Date()
      const timestamp = now.toTimeString().split(' ')[0]
      
      setLogs(prev => [
        ...prev,
        {
          id: Math.random().toString(),
          timestamp,
          level: "info",
          source,
          message: infos[Math.floor(Math.random() * infos.length)]
        }
      ])
    }, 8000)
    return () => clearInterval(interval)
  }, [])

  // Handle human-in-the-loop ticket approval/rejection
  const handleTicketApproval = (ticketId: string, approved: boolean) => {
    const ticket = hitlTickets.find(t => t.id === ticketId)
    if (!ticket) return

    const now = new Date()
    const timestamp = now.toTimeString().split(' ')[0]

    setHitlTickets(prev =>
      prev.map(t => t.id === ticketId ? { ...t, status: approved ? "approved" : "rejected" } : t)
    )

    if (approved) {
      // Update Kanban task status to done
      setTasks(prev =>
        prev.map(t => t.id === ticket.taskId ? { ...t, status: "done", progress: 100 } : t)
      )

      // Add to logs
      setLogs(prev => [
        ...prev,
        {
          id: Math.random().toString(),
          timestamp,
          level: "success",
          source: ticket.agent,
          message: `HITL APPROVED: ${ticket.title} initiated. Status: Resolved.`
        }
      ])

      // Add agent chat message
      setChatMessages(prev => [
        ...prev,
        {
          id: Math.random().toString(),
          sender: "agent",
          agentName: ticket.agent,
          avatar: ticket.agentAvatar,
          message: `Thank you for the approval! ${ticket.title} has been verified and executed successfully. Pipeline health: 100%.`,
          timestamp
        }
      ])

      setTotalCost(prev => prev + 0.15)
    } else {
      // Update Kanban task status to In-Progress with lower progress
      setTasks(prev =>
        prev.map(t => t.id === ticket.taskId ? { ...t, status: "progress", progress: 40, priority: "high" } : t)
      )

      // Add to logs
      setLogs(prev => [
        ...prev,
        {
          id: Math.random().toString(),
          timestamp,
          level: "error",
          source: ticket.agent,
          message: `HITL REJECTED: ${ticket.title} aborted by operator request.`
        }
      ])

      // Add agent chat message
      setChatMessages(prev => [
        ...prev,
        {
          id: Math.random().toString(),
          sender: "agent",
          agentName: ticket.agent,
          avatar: ticket.agentAvatar,
          message: `Understood. The action for '${ticket.title}' has been rejected. I have reverted the task back to In-Progress for code refinement.`,
          timestamp
        }
      ])
    }
  }

  // Handle chat submission
  const handleChatSubmit = (e: React.FormEvent) => {
    e.preventDefault()
    if (!chatInput.trim()) return

    const now = new Date()
    const timestamp = now.toTimeString().split(' ')[0]

    const userMsg: ChatMessage = {
      id: Math.random().toString(),
      sender: "user",
      message: chatInput,
      timestamp
    }

    setChatMessages(prev => [...prev, userMsg])
    const currentInput = chatInput.toLowerCase()
    setChatInput("")
    setIsTyping(true)

    // Simulate Agent responses based on keyword input
    setTimeout(() => {
      let reply = ""
      let senderName = "Factory Lead"
      let avatar = "⚙️"

      if (currentInput.includes("cattlesync") || currentInput.includes("sync")) {
        senderName = "Cattlesync Agent"
        avatar = "🐮"
        reply = "I am actively monitoring the staging sync pipeline. DB schemas are 98% aligned. Would you like me to trigger a dry-run check or view full reports?"
      } else if (currentInput.includes("task") || currentInput.includes("kanban") || currentInput.includes("add")) {
        // Add a new task dynamically as proof of interaction!
        const newTaskId = "t" + (tasks.length + 1)
        const newTask: KanbanTask = {
          id: newTaskId,
          title: "Optimize API router compression weights",
          agent: "Performance Agent",
          agentAvatar: "⚡",
          status: "backlog",
          priority: "medium",
          progress: 0
        }
        setTasks(prev => [...prev, newTask])
        
        reply = `Certainly! I've added a new task to the backlog: "Optimize API router compression weights". You can check it under the Kanban Board view.`
        
        setLogs(prev => [
          ...prev,
          {
            id: Math.random().toString(),
            timestamp,
            level: "success",
            source: "System",
            message: `User created new backlog task: ${newTask.title}`
          }
        ])
      } else if (currentInput.includes("status") || currentInput.includes("health")) {
        const erpTicket = hitlTickets.find(t => t.id === "t1")
        const erpStatusStr = erpTicket?.status === "approved" ? "successfully approved" : erpTicket?.status === "rejected" ? "rejected" : "pending operator approval"
        reply = `The factory systems are currently healthy. Current CPU usage is ${cpuUsage}%, Memory load is ${memoryUsage}%. The ERP deployment task is ${erpStatusStr}.`
      } else if (currentInput.includes("settings") || currentInput.includes("rules") || currentInput.includes("scope")) {
        reply = `Current Factory Settings: Entity Name: "${companyName}", SDLC Strictness: Level ${strictnessLevel}. Unit tests are ${unitTestsEnforced ? "ENFORCED" : "OPTIONAL"}. Docs generation is ${docsGenerationEnforced ? "ENFORCED" : "OPTIONAL"}.`
      } else if (currentInput.includes("log") || currentInput.includes("error")) {
        reply = "There is one active warning regarding Jest runner memory leaks. I recommend scheduling an optimization run to profile the garbage collection cycle."
      } else {
        reply = "I've registered your instructions. Initiating a scan on active agent channels. Let me know if you want me to update the Kanban board, trigger logs, or check telemetry."
      }

      setChatMessages(prev => [
        ...prev,
        {
          id: Math.random().toString(),
          sender: "agent",
          agentName: senderName,
          avatar,
          message: reply,
          timestamp
        }
      ])
      setIsTyping(false)
      setTotalCost(prev => prev + 0.04)
    }, 1500)
  }

  // Filtered Logs
  const filteredLogs = logs.filter(log => {
    if (logFilter === "all") return true
    return log.level === logFilter
  })

  // Kanban task column sorting
  const getTasksByStatus = (status: KanbanTask["status"]) => {
    return tasks.filter(task => task.status === status)
  }

  return (
    <PageLayout
      className="max-w-7xl w-full mx-auto p-4 md:p-6 grid grid-cols-1 lg:grid-cols-4 gap-6 flex-grow"
      headerActions={
        <div className="flex items-center gap-6 text-xs font-mono text-muted-foreground">
          <div className="hidden xl:flex flex-col text-right">
            <span className="text-[10px] text-zinc-500">PROJECT WORKSPACE ID</span>
            <span className="text-white">{currentProject.workspaceId}</span>
          </div>
          <span className="text-white/10 hidden sm:inline">|</span>
          <div className="flex items-center gap-2">
            <span className="flex h-2 w-2 rounded-full bg-tertiary relative after:absolute after:inset-0 after:rounded-full after:bg-tertiary after:animate-ping"></span>
            <span className="text-[10px] font-semibold text-tertiary uppercase tracking-wider">Sync</span>
          </div>
          <span className="text-white/10 hidden sm:inline">|</span>
          <div className="flex flex-col text-right">
            <span className="text-[10px] text-zinc-500">USAGE (BYOK)</span>
            <span className="text-secondary font-bold font-sans text-sm">${totalCost.toFixed(2)}</span>
          </div>
        </div>
      }
    >
        
        {/* Left Sidebar: Telemetry & METRICS (1 Column wide on desktop) */}
        <div className="lg:col-span-1 flex flex-col gap-6">
          
          {/* HITL Human-in-the-Loop Interventions */}
          <Card className="border-secondary/20 bg-secondary/5 relative overflow-hidden flex flex-col">
            <div className="absolute top-0 left-0 right-0 h-1 bg-secondary animate-pulse"></div>
            <CardHeader className="pb-3 border-b border-secondary/15">
              <CardTitle className="text-secondary flex items-center justify-between text-xs font-mono uppercase tracking-wider font-bold">
                <span className="flex items-center gap-1.5">
                  <AlertTriangle className="size-4 shrink-0" />
                  HITL Intervention Queue
                </span>
                <span className="bg-secondary/20 text-secondary text-[10px] px-1.5 py-0.5 rounded-full font-sans font-bold">
                  {hitlTickets.filter(t => t.status === "pending").length} Pending
                </span>
              </CardTitle>
            </CardHeader>
            <CardContent className="p-0 divide-y divide-secondary/10 max-h-[400px] overflow-y-auto">
              {hitlTickets.map(ticket => {
                const isPending = ticket.status === "pending"
                return (
                  <div key={ticket.id} className="p-4 flex flex-col gap-3 transition-colors hover:bg-secondary/10">
                    <div className="flex justify-between items-start gap-2">
                      <div className="flex flex-col">
                        <span className="text-[10px] font-mono text-zinc-400 uppercase tracking-widest">{ticket.agent}</span>
                        <h4 className="text-xs font-bold text-white mt-0.5">{ticket.title}</h4>
                      </div>
                      <span className="text-sm shrink-0 select-none bg-[#0a0f1d] size-6 rounded-full flex items-center justify-center border border-border/10">
                        {ticket.agentAvatar}
                      </span>
                    </div>
                    <p className="text-[11px] text-zinc-300 leading-relaxed bg-[#060b13]/50 p-2 rounded border border-border/5">
                      {ticket.description}
                    </p>
                    
                    {isPending ? (
                      <div className="flex gap-2 justify-end pt-1">
                        <Button 
                          size="xs" 
                          variant="destructive" 
                          onClick={() => handleTicketApproval(ticket.id, false)}
                          className="font-mono text-[9px] h-7 px-2.5"
                        >
                          <X className="size-3" />
                          REJECT
                        </Button>
                        <Button 
                          size="xs" 
                          onClick={() => handleTicketApproval(ticket.id, true)}
                          className="bg-secondary text-secondary-foreground hover:bg-secondary/80 font-mono text-[9px] h-7 px-2.5"
                        >
                          <Check className="size-3" />
                          APPROVE
                        </Button>
                      </div>
                    ) : (
                      <div className="flex items-center gap-1.5 text-[10px] font-mono justify-end">
                        <span className="text-zinc-500">DECISION:</span>
                        <span className={`font-bold uppercase ${ticket.status === "approved" ? "text-tertiary" : "text-destructive"}`}>
                          {ticket.status}
                        </span>
                        {ticket.status === "approved" ? <Check className="size-3 text-tertiary" /> : <X className="size-3 text-destructive" />}
                      </div>
                    )}
                  </div>
                )
              })}
              {hitlTickets.length === 0 && (
                <div className="p-8 text-center text-xs text-muted-foreground">
                  No HITL tickets configured.
                </div>
              )}
            </CardContent>
          </Card>

          {/* Live Telemetry Card */}
          <Card>
            <CardHeader className="border-b border-border/10 pb-3">
              <CardTitle className="text-sm font-bold flex items-center gap-2">
                <Activity className="size-4 text-primary" />
                Live Telemetry
              </CardTitle>
              <CardDescription className="text-[10px] font-mono text-muted-foreground uppercase">
                Ghost in the Machine Logs
              </CardDescription>
            </CardHeader>
            <CardContent className="pt-4 flex flex-col gap-4">
              
              {/* CPU */}
              <div className="flex flex-col gap-1.5">
                <div className="flex justify-between items-center text-xs font-mono">
                  <span className="flex items-center gap-1.5 text-muted-foreground"><Cpu className="size-3.5" /> CPU LOAD</span>
                  <span className="font-bold text-white">{cpuUsage}%</span>
                </div>
                <div className="w-full bg-muted h-1.5 rounded-full overflow-hidden">
                  <div 
                    className="bg-primary h-full transition-all duration-1000" 
                    style={{ width: `${cpuUsage}%` }}
                  ></div>
                </div>
              </div>

              {/* Memory */}
              <div className="flex flex-col gap-1.5">
                <div className="flex justify-between items-center text-xs font-mono">
                  <span className="flex items-center gap-1.5 text-muted-foreground"><Database className="size-3.5" /> MEMORY UTIL</span>
                  <span className="font-bold text-white">{memoryUsage}%</span>
                </div>
                <div className="w-full bg-muted h-1.5 rounded-full overflow-hidden">
                  <div 
                    className="bg-tertiary h-full transition-all duration-1000" 
                    style={{ width: `${memoryUsage}%` }}
                  ></div>
                </div>
              </div>

              {/* Latency */}
              <div className="flex justify-between items-center border-t border-border/10 pt-3 text-xs font-mono">
                <span className="text-muted-foreground">NODE LATENCY:</span>
                <span className="text-white font-bold">{latency} ms</span>
              </div>

              {/* Active instances */}
              <div className="flex justify-between items-center text-xs font-mono">
                <span className="text-muted-foreground">RUNNING AGENTS:</span>
                <span className="text-primary font-bold">{activeAgentsCount} nodes</span>
              </div>
            </CardContent>
          </Card>

          {/* System Overview Details */}
          <Card className="bg-surface-container/50">
            <CardHeader className="pb-2">
              <CardTitle className="text-xs text-muted-foreground font-mono uppercase">
                Active Modules Summary
              </CardTitle>
            </CardHeader>
            <CardContent className="text-xs font-mono flex flex-col gap-2.5">
              <div className="flex justify-between">
                <span className="text-muted-foreground">Cattlesync Sync:</span>
                <Badge className="bg-tertiary/10 text-tertiary border-tertiary/20 hover:bg-tertiary/20">Synced</Badge>
              </div>
              <div className="flex justify-between">
                <span className="text-muted-foreground">ERP Deployment:</span>
                {(() => {
                  const erpTicket = hitlTickets.find(t => t.id === "t1")
                  const isApproved = erpTicket?.status === "approved"
                  const isRejected = erpTicket?.status === "rejected"
                  
                  let badgeColor = "bg-secondary/10 text-secondary border-secondary/20 font-bold"
                  let badgeText = "Suspended"
                  if (isApproved) {
                    badgeColor = "bg-tertiary/10 text-tertiary border-tertiary/20 font-bold"
                    badgeText = "Deployed"
                  } else if (isRejected) {
                    badgeColor = "bg-destructive/10 text-destructive border-destructive/20 font-bold"
                    badgeText = "Rejected"
                  }
                  
                  return (
                    <Badge className={badgeColor}>
                      {badgeText}
                    </Badge>
                  )
                })()}
              </div>
              <div className="flex justify-between">
                <span className="text-muted-foreground">QA Leak Check:</span>
                <Badge className="bg-secondary/10 text-secondary border-secondary/20 hover:bg-secondary/20">Investigating</Badge>
              </div>
            </CardContent>
          </Card>

        </div>

        {/* Right Side: Interaction Console & Workspace Tabs (3 Columns wide) */}
        <div className="lg:col-span-3 flex flex-col gap-6">
          
          <Tabs value={activeTab} onValueChange={setActiveTab} className="w-full">
            <div className="flex items-center justify-between border-b border-border/40 pb-2 mb-4">
              <TabsList className="bg-muted/50 p-0.5">
                <TabsTrigger value="overview" className="data-active:bg-background">
                  <LayoutDashboard className="size-4" data-icon="inline-start" />
                  Overview
                </TabsTrigger>
                <TabsTrigger value="kanban" className="data-active:bg-background">
                  <KanbanSquare className="size-4" data-icon="inline-start" />
                  Kanban Board
                </TabsTrigger>
                <TabsTrigger value="files" className="data-active:bg-background">
                  <FolderTree className="size-4" data-icon="inline-start" />
                  File Manager
                </TabsTrigger>
                <TabsTrigger value="logs" className="data-active:bg-background">
                  <Terminal className="size-4" data-icon="inline-start" />
                  Live Logs
                </TabsTrigger>
                <TabsTrigger value="chat" className="data-active:bg-background">
                  <MessageSquare className="size-4" data-icon="inline-start" />
                  Agent Chat
                </TabsTrigger>
                <TabsTrigger value="settings" className="data-active:bg-background">
                  <Settings className="size-4" data-icon="inline-start" />
                  Settings
                </TabsTrigger>
              </TabsList>
              
              <div className="hidden sm:flex items-center gap-2">
                <span className="text-xs font-mono text-muted-foreground">Current View:</span>
                <Badge variant="outline" className="border-border font-mono text-[10px] text-white">
                  {activeTab.toUpperCase()}
                </Badge>
              </div>
            </div>

            {/* TAB: PROJECT OVERVIEW (this project's own dashboard) */}
            <TabsContent value="overview" className="mt-0 space-y-6">
              {/* Important Notices (this project only) */}
              <div className="space-y-3">
                <h3 className="text-xs font-mono uppercase tracking-wider text-zinc-400">Important Notices</h3>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  {projectActivity.alerts.map((alert, index) => {
                    const isError = alert.type === "error"
                    const isWarn = alert.type === "warn"
                    return (
                      <div
                        key={index}
                        className={`bg-surface-container-low/40 border backdrop-blur-md p-4 rounded-xl flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4 transition-all border-t-2 ${
                          isError
                            ? "border-t-destructive border-destructive/20 hover:border-destructive/40"
                            : isWarn
                            ? "border-t-secondary border-secondary/20 hover:border-secondary/40"
                            : "border-t-primary border-primary/20 hover:border-primary/40"
                        }`}
                      >
                        <div className="flex items-start gap-3">
                          <div className={`p-1.5 rounded-lg ${isError ? "bg-destructive/10 text-destructive" : isWarn ? "bg-secondary/10 text-secondary" : "bg-primary/10 text-primary"}`}>
                            {isError ? <XCircle className="size-5" /> : <AlertTriangle className="size-5" />}
                          </div>
                          <div>
                            <p className={`font-mono text-[10px] font-bold tracking-wider ${isError ? "text-destructive" : isWarn ? "text-secondary" : "text-primary"}`}>
                              {alert.title}
                            </p>
                            <p className="text-sm text-zinc-300 font-medium mt-0.5">{alert.desc}</p>
                          </div>
                        </div>
                        <button
                          onClick={() => setActiveTab(alert.tab)}
                          className={`shrink-0 px-4 py-1.5 rounded font-mono text-xs font-bold transition-all flex items-center gap-1.5 ${
                            isError
                              ? "border border-destructive text-destructive hover:bg-destructive/10"
                              : isWarn
                              ? "bg-secondary text-background hover:brightness-110"
                              : "bg-primary text-background hover:brightness-110"
                          }`}
                        >
                          <span>{alert.action}</span>
                          <ArrowRight className="size-3.5" />
                        </button>
                      </div>
                    )
                  })}
                  {projectActivity.alerts.length === 0 && (
                    <div className="col-span-2 bg-surface-container-low/20 border border-border/10 p-6 rounded-xl text-center text-zinc-500 font-mono text-xs">
                      No active alerts or manual approvals pending for this project.
                    </div>
                  )}
                </div>
              </div>

              {/* Stats Strip (this project only) */}
              <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">
                <div className="bg-surface-container-low/40 border border-border/20 backdrop-blur-md p-5 rounded-xl flex flex-col justify-between h-24">
                  <span className="font-mono text-[10px] text-zinc-500 uppercase tracking-widest">Tasks Completed</span>
                  <div>
                    <div className="text-xl font-black text-white tracking-tight mb-1.5">
                      {currentProject.progress}/{currentProject.maxProgress}
                    </div>
                    <div className="w-full bg-background h-1 rounded-full overflow-hidden">
                      <div className="bg-primary h-full" style={{ width: `${(currentProject.progress / currentProject.maxProgress) * 100}%` }}></div>
                    </div>
                  </div>
                </div>
                <div className="bg-surface-container-low/40 border border-border/20 backdrop-blur-md p-5 rounded-xl flex flex-col justify-between h-24">
                  <span className="font-mono text-[10px] text-zinc-500 uppercase tracking-widest">Active Agent</span>
                  <div className="text-lg font-black text-white">{currentProject.agentIcon} {currentProject.agentName}</div>
                </div>
                <div className="bg-surface-container-low/40 border border-border/20 backdrop-blur-md p-5 rounded-xl flex flex-col justify-between h-24">
                  <span className="font-mono text-[10px] text-zinc-500 uppercase tracking-widest">Usage (BYOK)</span>
                  <div className="text-xl font-black text-primary tracking-tight">{currentProject.totalSpend}</div>
                </div>
                <div className="bg-surface-container-low/40 border border-border/20 backdrop-blur-md p-5 rounded-xl flex flex-col justify-between h-24">
                  <span className="font-mono text-[10px] text-zinc-500 uppercase tracking-widest">Status</span>
                  <div className="text-sm font-bold text-white">{currentProject.status}</div>
                </div>
              </div>

              {/* Recent Activity (this project only) */}
              <div className="bg-surface-container-low/40 border border-border/20 backdrop-blur-md rounded-xl overflow-hidden">
                <div className="p-4 border-b border-border/10 flex items-center gap-2 bg-surface-container-low/20">
                  <History className="size-4 text-primary" />
                  <h3 className="font-mono text-[10px] uppercase tracking-wider font-bold text-zinc-400">Recent Activity</h3>
                </div>
                <div className="p-4 font-mono text-[11px] space-y-3">
                  {projectActivity.logs.map((log, idx) => (
                    <div key={idx} className="flex gap-2.5 items-start">
                      <span className="text-zinc-600 shrink-0">[{log.time}]</span>
                      <span className={`font-bold shrink-0 text-[10px] ${
                        log.level === "FAIL" ? "text-destructive" : log.level === "WARN" ? "text-secondary" : log.level === "SUCCESS" ? "text-tertiary" : "text-primary"
                      }`}>
                        {log.level}
                      </span>
                      <span className="text-zinc-300 truncate">{log.text}</span>
                    </div>
                  ))}
                </div>
              </div>
            </TabsContent>

            {/* TAB 1: KANBAN BOARD */}
            <TabsContent value="kanban" className="mt-0">
              <div className="grid grid-cols-1 md:grid-cols-5 gap-4">
                
                {/* Column 1: Backlog */}
                <div className="flex flex-col gap-3">
                  <div className="flex items-center justify-between border-b border-border/20 pb-2">
                    <span className="text-xs font-mono font-bold text-muted-foreground uppercase flex items-center gap-1.5">
                      <Circle className="size-3 text-slate-500 fill-slate-500" />
                      Backlog ({getTasksByStatus("backlog").length})
                    </span>
                    <Button 
                      size="icon-xs" 
                      variant="ghost"
                      onClick={() => {
                        const newTaskId = "t" + (tasks.length + 1)
                        const newTask: KanbanTask = {
                          id: newTaskId,
                          title: "Flush cache logs and optimize buffers",
                          agent: "System Agent",
                          agentAvatar: "🤖",
                          status: "backlog",
                          priority: "low",
                          progress: 0
                        }
                        setTasks(prev => [...prev, newTask])
                      }}
                    >
                      <Plus className="size-3" />
                    </Button>
                  </div>
                  
                  <div className="flex flex-col gap-3 min-h-[300px]">
                    {getTasksByStatus("backlog").map(task => (
                      <TaskCard key={task.id} task={task} />
                    ))}
                    {getTasksByStatus("backlog").length === 0 && (
                      <div className="text-center py-8 text-xs text-muted-foreground border border-dashed border-border/20 rounded-lg">
                        No backlog tasks
                      </div>
                    )}
                  </div>
                </div>

                {/* Column 2: In-Progress */}
                <div className="flex flex-col gap-3">
                  <div className="border-b border-border/20 pb-2">
                    <span className="text-xs font-mono font-bold text-secondary uppercase flex items-center gap-1.5">
                      <Circle className="size-3 text-secondary fill-secondary" />
                      In-Progress ({getTasksByStatus("progress").length})
                    </span>
                  </div>
                  
                  <div className="flex flex-col gap-3 min-h-[300px]">
                    {getTasksByStatus("progress").map(task => (
                      <TaskCard key={task.id} task={task} />
                    ))}
                    {getTasksByStatus("progress").length === 0 && (
                      <div className="text-center py-8 text-xs text-muted-foreground border border-dashed border-border/20 rounded-lg">
                        No active tasks
                      </div>
                    )}
                  </div>
                </div>

                {/* Column 3: Auditing */}
                <div className="flex flex-col gap-3">
                  <div className="border-b border-border/20 pb-2">
                    <span className="text-xs font-mono font-bold text-purple-400 uppercase flex items-center gap-1.5">
                      <Circle className="size-3 text-purple-400 fill-purple-400" />
                      Auditing ({getTasksByStatus("auditing").length})
                    </span>
                  </div>
                  
                  <div className="flex flex-col gap-3 min-h-[300px]">
                    {getTasksByStatus("auditing").map(task => (
                      <TaskCard key={task.id} task={task} />
                    ))}
                    {getTasksByStatus("auditing").length === 0 && (
                      <div className="text-center py-8 text-xs text-muted-foreground border border-dashed border-border/20 rounded-lg">
                        No tasks in audit
                      </div>
                    )}
                  </div>
                </div>

                {/* Column 4: Human Verification */}
                <div className="flex flex-col gap-3">
                  <div className="border-b border-border/20 pb-2">
                    <span className="text-xs font-mono font-bold text-blue-400 uppercase flex items-center gap-1.5">
                      <Circle className="size-3 text-blue-400 fill-blue-400" />
                      Verification ({getTasksByStatus("verification").length})
                    </span>
                  </div>
                  
                  <div className="flex flex-col gap-3 min-h-[300px]">
                    {getTasksByStatus("verification").map(task => (
                      <TaskCard key={task.id} task={task} />
                    ))}
                    {getTasksByStatus("verification").length === 0 && (
                      <div className="text-center py-8 text-xs text-muted-foreground border border-dashed border-border/20 rounded-lg">
                        No pending verify
                      </div>
                    )}
                  </div>
                </div>

                {/* Column 5: Done */}
                <div className="flex flex-col gap-3">
                  <div className="border-b border-border/20 pb-2">
                    <span className="text-xs font-mono font-bold text-tertiary uppercase flex items-center gap-1.5">
                      <Circle className="size-3 text-tertiary fill-tertiary" />
                      Done ({getTasksByStatus("done").length})
                    </span>
                  </div>
                  
                  <div className="flex flex-col gap-3 min-h-[300px]">
                    {getTasksByStatus("done").map(task => (
                      <TaskCard key={task.id} task={task} />
                    ))}
                    {getTasksByStatus("done").length === 0 && (
                      <div className="text-center py-8 text-xs text-muted-foreground border border-dashed border-border/20 rounded-lg">
                        Empty column
                      </div>
                    )}
                  </div>
                </div>

              </div>
            </TabsContent>

            {/* TAB: FILE MANAGER */}
            <TabsContent value="files" className="mt-0">
              <Card className="border border-border/40 rounded-xl flex flex-col md:flex-row h-[500px] overflow-hidden p-0">

                {/* File Tree Panel */}
                <div className="w-full md:w-64 shrink-0 border-b md:border-b-0 md:border-r border-border/40 bg-surface-container-low/30 flex flex-col">
                  <div className="px-3 py-2.5 border-b border-border/20 flex items-center gap-2">
                    <FolderTree className="size-3.5 text-primary" />
                    <span className="font-mono text-[10px] uppercase tracking-wider text-muted-foreground">
                      workspace/
                    </span>
                  </div>
                  <div className="flex-1 overflow-y-auto p-2">
                    {workspaceFileTree.map(node => (
                      <FileTreeItem
                        key={node.path}
                        node={node}
                        depth={0}
                        expandedFolders={expandedFolders}
                        selectedFilePath={selectedFilePath}
                        onToggleFolder={handleToggleFolder}
                        onSelectFile={handleSelectFile}
                      />
                    ))}
                  </div>
                </div>

                {/* Editor Panel */}
                <div className="flex-1 flex flex-col min-w-0">
                  <div className="px-4 py-2.5 border-b border-border/20 flex items-center justify-between gap-3 bg-surface-container-low/10">
                    <span className="font-mono text-xs text-white truncate flex items-center gap-2">
                      <FileCode className="size-3.5 text-primary shrink-0" />
                      {selectedFilePath}
                      {isFileDirty && <span className="text-secondary text-[10px] font-bold">● unsaved</span>}
                    </span>
                    <div className="flex items-center gap-2 shrink-0">
                      {fileSaveStatus && (
                        <span className="text-[10px] font-mono text-tertiary flex items-center gap-1">
                          <Check className="size-3" /> {fileSaveStatus}
                        </span>
                      )}
                      <Button
                        size="xs"
                        variant="ghost"
                        onClick={handleDiscardFileEdit}
                        disabled={!isFileDirty}
                        className="font-mono text-[10px]"
                      >
                        Discard
                      </Button>
                      <Button
                        size="xs"
                        variant="default"
                        onClick={handleSaveFile}
                        disabled={!isFileDirty}
                        className="font-mono text-[10px] flex items-center gap-1"
                      >
                        <Save className="size-3" />
                        Save
                      </Button>
                    </div>
                  </div>
                  <textarea
                    value={draftContent}
                    onChange={(e) => setDraftContent(e.target.value)}
                    spellCheck={false}
                    className="flex-1 w-full bg-black text-zinc-200 font-mono text-xs p-4 resize-none focus:outline-none leading-relaxed"
                  />
                </div>
              </Card>
            </TabsContent>

            {/* TAB 2: LIVE LOGS TERMINAL */}
            <TabsContent value="logs" className="mt-0">
              <Card className="bg-black border border-border/40 rounded-xl flex flex-col h-[500px]">
                
                {/* Console Top Action Bar */}
                <div className="bg-zinc-950 border-b border-border/20 px-4 py-3 flex flex-wrap justify-between items-center gap-3">
                  <div className="flex items-center gap-3">
                    <div className="flex gap-1.5">
                      <span className="w-2.5 h-2.5 rounded-full bg-red-500"></span>
                      <span className="w-2.5 h-2.5 rounded-full bg-amber-500"></span>
                      <span className="w-2.5 h-2.5 rounded-full bg-green-500"></span>
                    </div>
                    <span className="font-mono text-xs text-muted-foreground flex items-center gap-1.5">
                      <Terminal className="size-3.5 text-primary" />
                      factory-orchestrator-shell
                    </span>
                  </div>
                  
                  {/* Filter buttons */}
                  <div className="flex items-center gap-2">
                    <Button 
                      size="xs" 
                      variant={logFilter === "all" ? "default" : "ghost"}
                      onClick={() => setLogFilter("all")}
                      className="font-mono text-[10px]"
                    >
                      All
                    </Button>
                    <Button 
                      size="xs" 
                      variant={logFilter === "info" ? "default" : "ghost"}
                      onClick={() => setLogFilter("info")}
                      className="font-mono text-[10px] text-primary"
                    >
                      Info
                    </Button>
                    <Button 
                      size="xs" 
                      variant={logFilter === "warning" ? "default" : "ghost"}
                      onClick={() => setLogFilter("warning")}
                      className="font-mono text-[10px] text-secondary"
                    >
                      Warn
                    </Button>
                    <Button 
                      size="xs" 
                      variant={logFilter === "error" ? "default" : "ghost"}
                      onClick={() => setLogFilter("error")}
                      className="font-mono text-[10px] text-destructive"
                    >
                      Error
                    </Button>
                    <Button 
                      size="xs" 
                      variant={logFilter === "success" ? "default" : "ghost"}
                      onClick={() => setLogFilter("success")}
                      className="font-mono text-[10px] text-tertiary"
                    >
                      Success
                    </Button>
                  </div>
                </div>

                {/* Console Output Stream */}
                <div className="flex-1 p-4 overflow-y-auto font-mono text-xs flex flex-col gap-2 bg-black select-text">
                  {filteredLogs.map(log => {
                    let levelColor = "text-muted-foreground"
                    if (log.level === "success") levelColor = "text-tertiary"
                    if (log.level === "warning") levelColor = "text-secondary font-semibold"
                    if (log.level === "error") levelColor = "text-destructive font-semibold"

                    return (
                      <div key={log.id} className="flex gap-4 hover:bg-white/5 py-0.5 px-1 rounded transition-colors">
                        <span className="text-zinc-600 select-none">{log.timestamp}</span>
                        <span className={`w-14 uppercase font-semibold shrink-0 select-none ${levelColor}`}>
                          [{log.level}]
                        </span>
                        <span className="text-primary/70 w-24 shrink-0 select-none">
                          {log.source}:
                        </span>
                        <span className="text-zinc-300 break-all">{log.message}</span>
                      </div>
                    )
                  })}
                  <div ref={logsEndRef}></div>
                </div>

                {/* Footer Console Control */}
                <div className="bg-zinc-950 border-t border-border/20 px-4 py-2.5 flex justify-between items-center text-[10px] font-mono text-zinc-500">
                  <span>Press ESC to focus terminal input</span>
                  <div className="flex items-center gap-2">
                    <span className="h-1.5 w-1.5 bg-tertiary rounded-full animate-pulse"></span>
                    <span>ONLINE</span>
                  </div>
                </div>
              </Card>
            </TabsContent>

            {/* TAB 3: AGENT CHAT */}
            <TabsContent value="chat" className="mt-0">
              <Card className="border border-border/40 rounded-xl flex flex-col h-[500px]">
                
                {/* Chat header */}
                <div className="px-4 py-3 border-b border-border/10 flex items-center justify-between bg-surface-container/50">
                  <div className="flex items-center gap-3">
                    <span className="text-xl">⚙️</span>
                    <div>
                      <h4 className="text-sm font-semibold text-white">Factory Lead Orchestrator</h4>
                      <p className="text-[10px] text-muted-foreground font-mono">AUTONOMOUS COORDINATOR CHANNEL</p>
                    </div>
                  </div>
                  <Badge variant="outline" className="border-tertiary/20 text-tertiary font-mono text-[10px]">
                    ONLINE
                  </Badge>
                </div>

                {/* Chat Messages Scroll Container */}
                <div className="flex-1 p-4 overflow-y-auto flex flex-col gap-4 bg-background/20">
                  {chatMessages.map(msg => {
                    const isAgent = msg.sender === "agent"
                    return (
                      <div 
                        key={msg.id} 
                        className={`flex gap-3 max-w-[85%] ${!isAgent ? "ml-auto flex-row-reverse" : ""}`}
                      >
                        {isAgent && (
                          <div className="w-8 h-8 rounded-lg bg-surface flex items-center justify-center border border-border text-sm shrink-0">
                            {msg.avatar || "🤖"}
                          </div>
                        )}
                        
                        <div className="flex flex-col gap-1">
                          {isAgent && (
                            <span className="text-[10px] font-mono text-primary font-bold">
                              {msg.agentName}
                            </span>
                          )}
                          <div className={`p-3 rounded-lg text-xs leading-relaxed ${
                            isAgent 
                              ? "bg-surface border border-border/60 text-zinc-100" 
                              : "bg-primary text-primary-foreground font-medium"
                          }`}>
                            {msg.message}
                          </div>
                          <span className={`text-[9px] font-mono text-zinc-600 ${!isAgent ? "text-right" : ""}`}>
                            {msg.timestamp}
                          </span>
                        </div>
                      </div>
                    )
                  })}
                  
                  {isTyping && (
                    <div className="flex gap-3 max-w-[85%]">
                      <div className="w-8 h-8 rounded-lg bg-surface flex items-center justify-center border border-border text-sm shrink-0">
                        🤖
                      </div>
                      <div className="flex flex-col gap-1">
                        <span className="text-[10px] font-mono text-primary font-bold">Agent processing</span>
                        <div className="p-3 rounded-lg bg-surface border border-border/60 text-xs text-muted-foreground flex gap-1.5 items-center">
                          <span className="w-1.5 h-1.5 bg-zinc-500 rounded-full animate-bounce"></span>
                          <span className="w-1.5 h-1.5 bg-zinc-500 rounded-full animate-bounce delay-100"></span>
                          <span className="w-1.5 h-1.5 bg-zinc-500 rounded-full animate-bounce delay-200"></span>
                        </div>
                      </div>
                    </div>
                  )}
                  <div ref={chatEndRef}></div>
                </div>

                {/* Chat Input Footer */}
                <form onSubmit={handleChatSubmit} className="p-3 border-t border-border/10 bg-surface/50 flex gap-2">
                  <input 
                    type="text" 
                    placeholder="Command active agents (e.g. 'cattlesync sync', 'add task', 'status')..." 
                    value={chatInput}
                    onChange={(e) => setChatInput(e.target.value)}
                    className="flex-1 bg-background border border-border/60 rounded-lg px-3.5 py-1.5 text-xs text-white focus:outline-none focus:border-primary placeholder:text-zinc-600"
                  />
                  <Button type="submit" size="sm" className="bg-primary text-primary-foreground font-mono text-xs">
                    <Send className="size-3.5" />
                    SEND
                  </Button>
                </form>

              </Card>
            </TabsContent>

            {/* TAB 4: FACTORY SETTINGS */}
            <TabsContent value="settings" className="mt-0">
              <Card className="border border-border/40 rounded-xl flex flex-col bg-surface/30">
                <div className="p-6 border-b border-border/10 flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4 bg-surface-container/50">
                  <div>
                    <h3 className="text-sm font-bold text-white flex items-center gap-2">
                      <Settings className="size-5 text-primary animate-spin-slow" />
                      Factory Configuration & Rules
                    </h3>
                    <p className="text-[11px] text-muted-foreground mt-0.5">
                      Define core behavioral limits and mission guidelines for autonomous agents.
                    </p>
                  </div>
                  <div className="flex gap-2">
                    <Button 
                      variant="outline" 
                      size="sm" 
                      onClick={() => {
                        setCompanyName("JSRM Enterprises Ltd.")
                        setMissionScope("Enterprise resource planning automation with a focus on supply chain transparency.")
                        setStrictnessLevel(4)
                        setUnitTestsEnforced(true)
                        setDocsGenerationEnforced(true)
                        setDdasEnabled(false)
                      }}
                      className="text-xs h-8"
                    >
                      Reset
                    </Button>
                    <Button 
                      size="sm" 
                      className="bg-primary text-primary-foreground font-mono font-bold text-xs h-8"
                      onClick={() => {
                        setIsSavingSettings(true)
                        setTimeout(() => {
                          setIsSavingSettings(false)
                          const now = new Date()
                          const timestamp = now.toTimeString().split(' ')[0]
                          setLogs(prev => [
                            ...prev,
                            {
                              id: Math.random().toString(),
                              timestamp,
                              level: "success",
                              source: "System",
                              message: `SETTINGS UPDATED: Strictness set to Level ${strictnessLevel}. Tests: ${unitTestsEnforced ? "ON" : "OFF"}.`
                            }
                          ])
                          setChatMessages(prev => [
                            ...prev,
                            {
                              id: Math.random().toString(),
                              sender: "agent",
                              agentName: "Factory Lead",
                              avatar: "⚙️",
                              message: `Factory rules updated. I have broadcasted the new configuration to all active sub-agents. Agent autonomy strictness level calibrated to ${strictnessLevel}/5.`,
                              timestamp
                            }
                          ])
                        }, 800)
                      }}
                      disabled={isSavingSettings}
                    >
                      {isSavingSettings ? "SAVING..." : "SAVE CHANGES"}
                    </Button>
                  </div>
                </div>

                <CardContent className="p-6 grid grid-cols-1 md:grid-cols-2 gap-6">
                  {/* Left Column: Organization Scope */}
                  <div className="flex flex-col gap-4">
                    <div className="space-y-2">
                      <label className="text-xs font-mono font-bold text-muted-foreground uppercase block">
                        Entity Name
                      </label>
                      <input 
                        type="text" 
                        value={companyName}
                        onChange={(e) => setCompanyName(e.target.value)}
                        className="w-full bg-background/50 border border-border/60 rounded-lg px-3.5 py-2 text-xs text-white focus:outline-none focus:border-primary placeholder:text-zinc-600"
                      />
                    </div>

                    <div className="space-y-2">
                      <label className="text-xs font-mono font-bold text-muted-foreground uppercase block">
                        Mission Scope Description
                      </label>
                      <textarea 
                        rows={4}
                        value={missionScope}
                        onChange={(e) => setMissionScope(e.target.value)}
                        className="w-full bg-background/50 border border-border/60 rounded-lg px-3.5 py-2 text-xs text-white focus:outline-none focus:border-primary resize-none placeholder:text-zinc-600"
                      />
                    </div>

                    <div className="space-y-2">
                      <label className="text-xs font-mono font-bold text-muted-foreground uppercase block">
                        Agent Communication Tone
                      </label>
                      <select 
                        value={voiceTone}
                        onChange={(e) => setVoiceTone(e.target.value)}
                        className="w-full bg-background/50 border border-border/60 rounded-lg px-3.5 py-2 text-xs text-white focus:outline-none focus:border-primary"
                      >
                        <option value="Technical Professional (High Density)">Technical Professional (High Density)</option>
                        <option value="Friendly Assistant">Friendly Assistant</option>
                        <option value="Strictly Formal">Strictly Formal</option>
                      </select>
                    </div>
                  </div>

                  {/* Right Column: Protocols & Constraints */}
                  <div className="flex flex-col gap-5">
                    
                    {/* SDLC Strictness slider */}
                    <div className="space-y-2.5">
                      <div className="flex justify-between items-center text-xs font-mono font-bold">
                        <span className="text-zinc-400 uppercase">SDLC Strictness level</span>
                        <span className="text-primary">LVL {strictnessLevel}</span>
                      </div>
                      <input 
                        type="range" 
                        min="1" 
                        max="5"
                        value={strictnessLevel}
                        onChange={(e) => {
                          const val = Number(e.target.value)
                          setStrictnessLevel(val)
                          localStorage.setItem("sdlc_strictness", String(val))
                          window.dispatchEvent(new Event("apex-settings-update"))
                        }}
                        className="w-full accent-primary bg-background/60 rounded-lg h-2 cursor-pointer"
                      />
                      <div className="flex justify-between font-mono text-[9px] text-muted-foreground">
                        <span>FLEXIBLE</span>
                        <span>STRICT RULES</span>
                      </div>
                    </div>

                    {/* Checkboxes/toggles */}
                    <div className="space-y-4 pt-2 border-t border-border/10">
                      
                      <div className="flex items-center justify-between">
                        <div className="flex flex-col">
                          <span className="text-xs font-semibold text-zinc-200">Enforce Unit Test Verification</span>
                          <span className="text-[10px] text-muted-foreground">Require test execution before merge</span>
                        </div>
                        <input 
                          type="checkbox"
                          checked={unitTestsEnforced}
                          onChange={(e) => setUnitTestsEnforced(e.target.checked)}
                          className="w-4 h-4 rounded text-primary bg-background border-border accent-primary focus:ring-primary focus:ring-1 cursor-pointer"
                        />
                      </div>

                      <div className="flex items-center justify-between">
                        <div className="flex flex-col">
                          <span className="text-xs font-semibold text-zinc-200">Enforce Automatic Docs Generation</span>
                          <span className="text-[10px] text-muted-foreground">Agents compile and update Markdown artifacts</span>
                        </div>
                        <input 
                          type="checkbox"
                          checked={docsGenerationEnforced}
                          onChange={(e) => setDocsGenerationEnforced(e.target.checked)}
                          className="w-4 h-4 rounded text-primary bg-background border-border accent-primary focus:ring-primary focus:ring-1 cursor-pointer"
                        />
                      </div>

                      <div className="flex items-center justify-between">
                        <div className="flex flex-col">
                          <span className="text-xs font-semibold text-zinc-200">Data-Delivery-as-Service (DDaS)</span>
                          <span className="text-[10px] text-muted-foreground">Integrate external API delivery nodes</span>
                        </div>
                        <input 
                          type="checkbox"
                          checked={ddasEnabled}
                          onChange={(e) => setDdasEnabled(e.target.checked)}
                          className="w-4 h-4 rounded text-primary bg-background border-border accent-primary focus:ring-primary focus:ring-1 cursor-pointer"
                        />
                      </div>

                    </div>

                  </div>

                  {/* Full-width Divider */}
                  <div className="col-span-1 md:col-span-2 border-t border-border/10 my-2 pt-4"></div>

                  {/* Pre-Flight Model Mapping Matrix */}
                  <div className="flex flex-col gap-4 col-span-1">
                    <div>
                      <h4 className="text-xs font-mono font-bold text-white flex items-center gap-1.5 uppercase">
                        <Sliders className="size-4 text-primary" />
                        Pre-Flight Model-to-Role Mapping
                      </h4>
                      <p className="text-[10px] text-muted-foreground mt-0.5">
                        Bind specialized LLM models to distinct agent operational profiles.
                      </p>
                    </div>

                    <div className="space-y-3 bg-[#070c14]/40 p-4 rounded-lg border border-border/10">
                      {/* Orchestrator */}
                      <div className="grid grid-cols-3 items-center gap-2">
                        <span className="text-[11px] font-mono font-semibold text-zinc-300">Orchestrator:</span>
                        <select
                          value={roleMappings.orchestrator}
                          onChange={(e) => setRoleMappings(prev => ({ ...prev, orchestrator: e.target.value }))}
                          className="col-span-2 bg-background/50 border border-border/60 rounded-md px-2 py-1 text-[11px] text-white focus:outline-none focus:border-primary cursor-pointer"
                        >
                          <option value="anthropic/claude-3-5-sonnet">Claude 3.5 Sonnet</option>
                          <option value="openai/gpt-4o">GPT-4o</option>
                          <option value="google/gemini-1.5-pro">Gemini 1.5 Pro</option>
                        </select>
                      </div>

                      {/* Coder */}
                      <div className="grid grid-cols-3 items-center gap-2">
                        <span className="text-[11px] font-mono font-semibold text-zinc-300">Coder Agent:</span>
                        <select
                          value={roleMappings.coder}
                          onChange={(e) => setRoleMappings(prev => ({ ...prev, coder: e.target.value }))}
                          className="col-span-2 bg-background/50 border border-border/60 rounded-md px-2 py-1 text-[11px] text-white focus:outline-none focus:border-primary cursor-pointer"
                        >
                          <option value="anthropic/claude-3-5-sonnet">Claude 3.5 Sonnet</option>
                          <option value="openai/gpt-4o">GPT-4o</option>
                          <option value="google/gemini-1.5-pro">Gemini 1.5 Pro</option>
                        </select>
                      </div>

                      {/* QA/Auditor */}
                      <div className="grid grid-cols-3 items-center gap-2">
                        <span className="text-[11px] font-mono font-semibold text-zinc-300">QA / Auditor:</span>
                        <select
                          value={roleMappings.auditor}
                          onChange={(e) => setRoleMappings(prev => ({ ...prev, auditor: e.target.value }))}
                          className="col-span-2 bg-background/50 border border-border/60 rounded-md px-2 py-1 text-[11px] text-white focus:outline-none focus:border-primary cursor-pointer"
                        >
                          <option value="google/gemini-1.5-pro">Gemini 1.5 Pro</option>
                          <option value="anthropic/claude-3-5-sonnet">Claude 3.5 Sonnet</option>
                          <option value="openai/gpt-4o">GPT-4o</option>
                        </select>
                      </div>

                      {/* Deployer */}
                      <div className="grid grid-cols-3 items-center gap-2">
                        <span className="text-[11px] font-mono font-semibold text-zinc-300">Deployer Agent:</span>
                        <select
                          value={roleMappings.deployer}
                          onChange={(e) => setRoleMappings(prev => ({ ...prev, deployer: e.target.value }))}
                          className="col-span-2 bg-background/50 border border-border/60 rounded-md px-2 py-1 text-[11px] text-white focus:outline-none focus:border-primary cursor-pointer"
                        >
                          <option value="openai/gpt-4o-mini">GPT-4o Mini</option>
                          <option value="anthropic/claude-3-5-haiku">Claude 3.5 Haiku</option>
                        </select>
                      </div>
                    </div>
                  </div>

                  {/* Skills / MCP Manager */}
                  <div className="flex flex-col gap-4 col-span-1">
                    <div>
                      <h4 className="text-xs font-mono font-bold text-white flex items-center gap-1.5 uppercase">
                        <Terminal className="size-4 text-secondary" />
                        Skills & MCP Tool Capabilities
                      </h4>
                      <p className="text-[10px] text-muted-foreground mt-0.5">
                        Activate sandbox features and filesystem capabilities for the swarm.
                      </p>
                    </div>

                    <div className="space-y-3 bg-[#070c14]/40 p-4 rounded-lg border border-border/10 max-h-[190px] overflow-y-auto">
                      {mcpSkills.map(skill => (
                        <div key={skill.id} className="flex items-center justify-between gap-3 text-xs">
                          <div className="flex flex-col">
                            <span className="font-mono font-bold text-zinc-200">{skill.name}</span>
                            <span className="text-[9px] text-muted-foreground">{skill.desc}</span>
                          </div>
                          <button
                            type="button"
                            onClick={() => {
                              setMcpSkills(prev => prev.map(s => s.id === skill.id ? { ...s, active: !s.active } : s))
                            }}
                            className={`px-2 py-0.5 rounded text-[10px] font-mono font-bold transition-all ${
                              skill.active 
                                ? "bg-secondary/20 text-secondary border border-secondary/30" 
                                : "bg-zinc-800 text-zinc-500 border border-zinc-700"
                            }`}
                          >
                            {skill.active ? "ACTIVE" : "DISABLED"}
                          </button>
                        </div>
                      ))}
                    </div>
                  </div>
                </CardContent>
              </Card>
            </TabsContent>

          </Tabs>

          {/* Lower Details Panel (BYOK usage & calibration) */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">

            <Card>
              <CardHeader className="pb-2">
                <CardTitle className="text-sm font-semibold flex items-center gap-2">
                  <DollarSign className="size-4 text-secondary" />
                  Usage Overview (BYOK)
                </CardTitle>
              </CardHeader>
              <CardContent className="text-xs text-muted-foreground leading-relaxed">
                Every agent runs on your own provider keys. Estimated consumption this session: <strong>${totalCost.toFixed(2)}</strong> (~$0.04/token execution). This is a spend estimate only — actual limits are governed by your provider account, not the platform.
              </CardContent>
            </Card>

            <Card>
              <CardHeader className="pb-2">
                <CardTitle className="text-sm font-semibold flex items-center gap-2">
                  <Sliders className="size-4 text-primary" />
                  System Calibration
                </CardTitle>
              </CardHeader>
              <CardContent className="flex flex-col gap-2">
                <div className="flex justify-between items-center text-xs font-mono">
                  <span>AGENT AUTONOMY DEPTH:</span>
                  <span className="text-primary font-bold">LVL 4</span>
                </div>
                <div className="flex justify-between items-center text-xs font-mono">
                  <span>SAFETY SHIELD MATRIX:</span>
                  <span className="text-tertiary font-bold">ONLINE</span>
                </div>
              </CardContent>
            </Card>

          </div>

        </div>

    </PageLayout>
  )
}

// Kanban Task Card Component
function TaskCard({ task }: { task: KanbanTask }) {
  let priorityColor = "bg-slate-500/10 text-slate-400 border-slate-500/20"
  if (task.priority === "medium") priorityColor = "bg-primary/10 text-primary border-primary/20"
  if (task.priority === "high") priorityColor = "bg-secondary/10 text-secondary border-secondary/20"
  if (task.priority === "critical") priorityColor = "bg-destructive/10 text-destructive border-destructive/20"

  return (
    <Card className="border border-border/40 bg-surface/50 hover:bg-surface transition-colors p-3.5 flex flex-col gap-3 group">
      <div className="flex justify-between items-start gap-2">
        <Badge variant="outline" className={`text-[9px] px-1.5 py-0.5 font-mono ${priorityColor}`}>
          {task.priority.toUpperCase()}
        </Badge>
        <span className="text-sm select-none">{task.agentAvatar}</span>
      </div>
      
      <p className="text-xs font-medium text-white group-hover:text-primary transition-colors leading-relaxed">
        {task.title}
      </p>

      <div className="flex flex-col gap-1.5 border-t border-border/10 pt-2.5">
        <div className="flex justify-between text-[10px] font-mono text-muted-foreground">
          <span>{task.agent}</span>
          <span className="font-bold">{task.progress}%</span>
        </div>
        <div className="w-full bg-background h-1 rounded-full overflow-hidden">
          <div 
            className="bg-primary h-full transition-all duration-500" 
            style={{ width: `${task.progress}%` }}
          ></div>
        </div>
      </div>
    </Card>
  )
}

// Recursive File Tree Item Component
function FileTreeItem({
  node,
  depth,
  expandedFolders,
  selectedFilePath,
  onToggleFolder,
  onSelectFile
}: {
  node: FileNode
  depth: number
  expandedFolders: Set<string>
  selectedFilePath: string
  onToggleFolder: (path: string) => void
  onSelectFile: (path: string) => void
}) {
  const isFolder = node.type === "folder"
  const isExpanded = expandedFolders.has(node.path)
  const isSelected = node.path === selectedFilePath

  return (
    <div>
      <button
        onClick={() => (isFolder ? onToggleFolder(node.path) : onSelectFile(node.path))}
        style={{ paddingLeft: `${depth * 14 + 8}px` }}
        className={`w-full flex items-center gap-1.5 py-1 pr-2 rounded text-xs font-mono transition-colors text-left ${
          isSelected
            ? "bg-primary/10 text-primary font-semibold"
            : "text-muted-foreground hover:bg-white/5 hover:text-white"
        }`}
      >
        {isFolder ? (
          <>
            {isExpanded ? <ChevronDown className="size-3 shrink-0" /> : <ChevronRight className="size-3 shrink-0" />}
            {isExpanded ? <FolderOpen className="size-3.5 shrink-0 text-secondary" /> : <Folder className="size-3.5 shrink-0 text-secondary" />}
          </>
        ) : (
          <>
            <span className="w-3 shrink-0" />
            <FileCode className="size-3.5 shrink-0 text-primary/70" />
          </>
        )}
        <span className="truncate">{node.name}</span>
      </button>

      {isFolder && isExpanded && node.children?.map(child => (
        <FileTreeItem
          key={child.path}
          node={child}
          depth={depth + 1}
          expandedFolders={expandedFolders}
          selectedFilePath={selectedFilePath}
          onToggleFolder={onToggleFolder}
          onSelectFile={onSelectFile}
        />
      ))}
    </div>
  )
}

export default function Workspace() {
  return (
    <Suspense fallback={<div className="min-h-screen bg-background flex items-center justify-center text-muted-foreground font-mono">LOADING WORKSPACE...</div>}>
      <WorkspaceContent />
    </Suspense>
  )
}
